######################################################
#          HTTP Tests for Cargonaut Server          #
######################################################


######################################################
#                Static routes                    #
######################################################
### get / --> Angular Project
GET http://localhost:4200/ HTTP/1.1

######################################################
#                Authentication                    #
######################################################
### correct login
POST http://localhost:4200/api/login HTTP/1.1
Content-Type: application/json
Cookie:

{
  "email": "admin@admin.de",
  "password": "admin"
}

### incorrect login -> Falsches Passwort
POST http://localhost:4200/api/login HTTP/1.1
Content-Type: application/json
Cookie:

{
  "email": "admin@admin.de",
  "password": "falschesPasswort"
}

###logout
POST http://localhost:4200/api/logout HTTP/1.1
Content-Type: application/json
Cookie:

### Register
POST http://localhost:4200/api/cargonaut HTTP/1.1
Content-Type: application/json
Cookie:

{
  "firstname": "Test",
  "lastname": "Tester",
  "password": "test",
  "email": "test@http.de",
  "birthday": "18-09-1998"
}

###logout
DELETE http://localhost:4200/api/cargonaut/30 HTTP/1.1


######################################################
#                Cargonaut                    #
######################################################
### get Cargonaut
GET http://localhost:4200/api/cargonaut/5 HTTP/1.1
Cookie:

### get Cargonaut - nicht vorhanden
GET http://localhost:4200/api/cargonaut/0 HTTP/1.1
Cookie:

### Update Cargonaut
PUT http://localhost:4200/api/cargonaut/8 HTTP/1.1
Content-Type: application/json
Cookie:

{
  "firstname": "Teston",
  "lastname": "Testermann",
  "email": "test@tester.de"
}

### Update Cargonaut - only 1 parameter
PUT http://localhost:4200/api/cargonaut/8 HTTP/1.1
Content-Type: application/json
Cookie:

{
  "email": "test@teston.de"
}

### Update Cargonaut - user nicht vorhanden
PUT http://localhost:4200/api/cargonaut/0 HTTP/1.1
Content-Type: application/json
Cookie:

{
  "email": "test@teston.de"
}


######################################################
#                Fahrzeuge                    #
######################################################
### post vehicle
POST http://localhost:4200/api/vehicle/5 HTTP/1.1
Content-Type: application/json
Cookie:

{
  "type": "Sprinter",
  "seats": 3,
  "length": 200,
  "width": 100,
  "height": 100
}

### get vehicle
GET http://localhost:4200/api/vehicle/5 HTTP/1.1
Cookie:

### get vehicles from cargonaut
GET http://localhost:4200/api/vehicles/5 HTTP/1.1
Cookie:

### get vehicles from cargonaut
DELETE http://localhost:4200/api/vehicle/6 HTTP/1.1
Cookie:


######################################################
#                Post                    #
######################################################
### create Post
POST http://localhost:4200/api/post/5 HTTP/1.1
Content-Type: application/json
Cookie:

{
  "post": {
    "start_time": "0",
    "end_time": "0",
    "payment": "Bar",
    "vehicle": {
      "id": 4,
      "seats": 1
    },
    "description": "Testeetsttetsetestse esr tsetset e t t etset",
    "type": "Angebot",
    "price": 23.99,
    "startlocation": "Testort1",
    "endlocation": "Testort2",
    "hold": {
      "length": 123,
      "width": 123,
      "height": 56
    }
  }
}

### get post
GET http://localhost:4200/api/post/1 HTTP/1.1
Cookie:

### get posts
GET http://localhost:4200/api/posts HTTP/1.1
Cookie:

### Update Post
PUT http://localhost:4200/api/post/3 HTTP/1.1
Content-Type: application/json
Cookie:

{
  "startzeit": "",
  "ankunftZeit": "",
  "bezahlungsart": "EC",
  "vehicle": 5,
  "anzahlSitzplaetze": 9,
  "beschreibung": "TESTETSETEST  TEStsettete ste t",
  "price": 39.99
}


######################################################
#                Buchungen                  #
######################################################
### post Buchung
POST http://localhost:4200/api/buchung/5 HTTP/1.1

Cookie:

{
  "length": 20,
  "width": 20,
  "height": 20,
  "seats": 1,
  "post": 3
}

### get Buchungen
GET http://localhost:4200/api/buchungen/5 HTTP/1.1
Cookie:


######################################################
#                Bewertung                    #
######################################################
### post Bewertung
POST http://localhost:4200/api/bewertung/5 HTTP/1.1
Content-Type: application/json
Cookie:

{
  "fahrt": 1,
  "punktzahl": 5,
  "kommentar": "Wunderbare Fahrt!"
}

### get Bewertungen
GET http://localhost:4200/api/bewertungen/5 HTTP/1.1
Cookie:
